In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set_style('ticks')

import warnings
warnings.filterwarnings('ignore')

In [4]:
survey_data_hu = pd.read_csv(r'./Surveys/SmartLOCKMarketSurvey_HU.csv')
survey_data_de = pd.read_csv(r'./Surveys/SmartLOCKMarketSurvey_DE.csv')
survey_data_us = pd.read_csv(r'./Surveys/SmartLOCKMarketSurvey_US.csv')

In [18]:
survey_data_hu['location']='HU'
survey_data_de['location']='DE'
survey_data_us['location']='US'
survey_data_comb=survey_data_hu.append(survey_data_de, ignore_index=True).append(survey_data_us, ignore_index=True)

In [26]:
survey_data=survey_data_comb.groupby('location')
survey_data.head()

,Gender,Age,Area,Income,Feature,Brand,NumberOfDevices,Preference,Heard,ShoppingOnline,Unlock,location
0,Female,34,suburban,$100.000 to $150.000,Quality,None of these,NaN,Smart Features,Yes,35.0,Remote unlock by application,HU
1,Male,28,urban,$25.000 to $50.000,Safety,Apple Home Kit,5-10,Brand,No,26.0,Remote unlock by application,HU
2,Male,35,suburban,$75.000 to $100.000,Price,Google Home,1-5,Safety,No,39.0,NFC,HU
3,Male,24,rural,$100.000 to $150.000,Price,None of these,NaN,Remote Access,Yes,72.0,Remote unlock by application,HU
4,Female,29,urban,$50.000 to $75.000,Brand,None of these,NaN,Price,Yes,26.0,Biometrics - fingerprint,HU
1000,Male,37,suburban,$50.000 to $75.000,Quality,None of these,NaN,Price,No,68.0,Biometrics - fingerprint,DE
1001,Male,41,rural,$25.000 to $50.000,Quality,Fibaro,5-10,Smart Features,Yes,45.0,Biometrics - fingerprint,DE
1002,Female,40,rural,$50.000 to $75.000,Quality,Amazon Alexa,10-15,Remote Access,No,66.0,Remote unlock by application,DE
1003,Male,31,suburban,$50.000 to $75.000,Friend’s recommendation,iNels,1-5,Smart Features,No,80.0,Bluetooth,DE
1004,Male,49,rural,$150.000 or More,Price,Amazon Alexa,1-5,Remote Access,No,47.0,Remote unlock by application,DE
2000,Male,34,suburban,$75.000 to $100.000,Friend’s recommendation,None of these,NaN,Price,Yes,55.0,Biometrics - photo,US
2001,Female,44,suburban,$75.000 to $100.000,Safety,Loxone,10-15,Smart Features,Yes,39.0,Biometrics - eyescan,US
2002,Female,36,urban,$50.000 to $75.000,Durability,None of these,NaN,Price,Yes,NaN,Bluetooth,US
2003,Female,28,suburban,$25.000 to $50.000,Price,None of these,NaN,Smart Features,Yes,53.0,Biometrics - photo,US
2004,Male,28,urban,$75.000 to $100.000,Durability,iNels,1-5,Price,Yes,51.0,Biometrics - photo,US

In [27]:
def age_group(age):
    
    """Creates an age bucket for each participant using the age variable.
        Meant to be used on a DataFrame with .apply()."""
    
    # Convert to an int, in case the data is read in as an "object" (aka string)
    age = int(age)
    
    if age < 30:
        bucket = '<30'
    
    # Age 30 to 39 ('range' excludes upper bound)
    if age in range(30, 40):
        bucket = '30-39'
        
    if age in range(40, 50):
        bucket = '40-49'
        
    if age in range(50, 60):
        bucket = '50-59'
   
    if age >= 60:
        bucket = '60+'

    return bucket

In [28]:
def so_group(ShoppingOnline):
    
    """Creates an age bucket for each participant using the shopping_online variable.
        Meant to be used on a DataFrame with .apply()."""
    
    # Convert to an int, in case the data is read in as an "object" (aka string)
    so = ShoppingOnline
    
    if np.isnan(so):
        bucket = 'NaN'
        return bucket
    
    if so < 20:
        bucket = '<20'
    
    # Age 30 to 39 ('range' excludes upper bound)
    if so in range(20, 40):
        bucket = '20-39'
        
    if so in range(40, 60):
        bucket = '40-59'
        
    if so in range(60, 80):
        bucket = '50-59'
   
    if so >= 80:
        bucket = '>80'

    return bucket

In [46]:
def encode_income(income):
    """Takes a string indicating income and encodes it to an ordinal
    (numerical) variable."""
    x=0
    
    if income == '1-5':
        x = 1
        
    if income == '$25.000 to $50.000':
        x = 2
    
    if income == '$50.000 to $75.000':
        x = 3
        
    if income == '$75.000 to $100.000':
        x = 4
        
    if income == '$100.000 to $150.000':
        x = 5
        
    if income == '$150.000 or More':
        x = 6

    return x

In [47]:
def encode_ndev(ndev):
    """Takes a string indicating number of devices and encodes it to an ordinal
    (numerical) variable."""
    x=0 
    
    if ndev == '1-5':
        x = 1
        
    if ndev == '5-10':
        x = 2
    
    if ndev == '10-15':
        x = 3
        
    if ndev == '>15':
        x = 4
        

    return x

In [48]:
for col in survey_data.obj.columns:
    print(col+'\n')
    print(survey_data[col].describe())
    print(col+'\n')

Gender

         count unique     top freq
location
DE        1000      2    Male  526
HU        1000      2    Male  501
US        1000      2  Female  533
Gender

Age

           count    mean       std   min   25%   50%   75%   max
location
DE        1000.0  39.806  6.112424  23.0  36.0  39.0  44.0  66.0
HU        1000.0  32.192  5.923700  16.0  28.0  32.0  36.0  54.0
US        1000.0  35.017  5.865417  18.0  31.0  35.0  39.0  53.0
Age

Area

         count unique       top freq
location
DE        1000      3     urban  349
HU        1000      3     urban  455
US        1000      3  suburban  409
Area

Income

         count unique                   top freq
location
DE        1000      6      $150.000 or More  185
HU        1000      6    $25.000 to $50.000  188
US        1000      6  $100.000 to $150.000  177
Income

Feature

         count unique    top freq
location
DE        1000      8  Brand  183
HU        1000      8  Price  210
US        1000      8  Price  177
Feature

Brand

         count unique            top freq
location
DE        1000      8  None of these  363
HU        1000      7  None of these  457
US        1000      8  None of these  444
Brand

NumberOfDevices

         count unique   top freq
location
DE         567      4   1-5  206
HU         495      4  5-10  205
US         501      4   1-5  172
NumberOfDevices

Preference

         count unique     top freq
location
DE        1000      5  Safety  380
HU        1000      5  Safety  262
US        1000      5   Price  249
Preference

Heard

         count unique  top freq
location
DE        1000      2  Yes  569
HU        1000      2   No  529
US        1000      2  Yes  659
Heard

ShoppingOnline

          count       mean        std   min   25%   50%   75%    max
location
DE        894.0  55.361298  12.634774  28.0  46.0  54.0  63.0  109.0
HU        898.0  39.433185  14.507081   6.0  29.0  38.0  48.0  130.0
US        893.0  51.741321  14.037556  18.0  43.0  50.0  59.0  143.0
ShoppingOnline

Unlock

         count unique                           top freq
location
DE        1000      7  Remote unlock by application  203
HU        1000      7              Conventional key  235
US        1000      7      Biometrics - fingerprint  219
Unlock

location

         count unique top  freq
location
DE        1000      1  DE  1000
HU        1000      1  HU  1000
US        1000      1  US  1000
location